### PR TITLE
Bevy 0.10

### PR DESCRIPTION
**Pull request by hakolao**
@lecoqjacob I continued on your branch here. And updated the lib to be pretty much equal to `bevy_winit`'s current state (mostly copy)

Wanna take a look?

I also got rid of some unnecessary things like `pipeline_sync_data` (user can create one if they wish to split render into many systems).

### CODE REVIEW

**Comment by hakolao** [comment]
Also updated to latest vulkano

**Comment by hakolao** [comment]
Examples being my tests, this is much better now. Though I guess there could be more of them :)

**Comment by HexSleeves** [comment]
This definitely flows better now! Looks like upgrading cleaned up complex window creation architecture as well. Glad I could help a bit for you

**Comment by hakolao** [comment]
Gonna merge once the checks go through and do a release :). Thanks for pushing me to do this @lecoqjacob, wasn't too bad after all.

**Pull request merged**
