### PR TITLE
Bevy 0.10

### PR DESCRIPTION
**Pull request by HexSleeves**
I left some TODOs in the code for inspection on things i didnt know how to handle

### CODE REVIEW

**Comment by hakolao** [comment]
I’ll take a look later today, thanks :)

**Review by hakolao — COMMENTED** [review]
So, I originally had mostly copied `bevy_winit` and plugged in vulkano and the vulkano window renderer that holds the bevy window into that. Over time bevy and this plugin deviated a bunch, so I'm thinking that I just need to kind of redo that part and mostly copy the current state of `bevy_winit`.

I wish bevy made modification of the default app `runner` easier. I'll continue on this.

**Comment by HexSleeves** [comment]
I did some local testing and fixed a couple bugs that were popping up. Mainly in close window I now just pull the primary window entity and check against that. For the created window events, bevy added changed feature keeps triggering causing windows to be spawned constantly

**Comment by hakolao** [comment]
Did not know how to continue on this PR. So combined: https://github.com/hakolao/bevy_vulkano/pull/16.

**Pull request closed without merging**
